version: '3.8'

services:
  couchdb:
    image: karasevm/couchdb:3.3.2
    container_name: local-couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    volumes:
      - ./local.ini:/opt/couchdb/etc/local.ini    
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: secret_password
